-- CreateEnum
CREATE TYPE "Rank" AS ENUM ('TORAI', 'RAV_TORAI', 'SAMAL', 'SAMAL_RISHON', 'RAV_SAMAL', 'RAV_SAMAL_MITKADAM', 'RAV_SAMAL_BAKHIR', 'RAV_NAGAD_MISNE', 'RAV_NAGAD', 'SAGAN', 'SEREN', 'RAV_SEREN', 'SAGAN_ALUF', 'ALUF_MISHNE', 'TAT_ALUF', 'ALUF', 'RAV_ALUF');

-- AlterTable
ALTER TABLE "User" ADD COLUMN     "profileImage" TEXT,
ADD COLUMN     "rank" "Rank" NOT NULL DEFAULT 'TORAI';
